=== jccheesman/alaska-fuel-agents-demo/build/schemas/hubs.json.schema.json
{
 "type": "object",
 "properties": {
  "n": {
   "const": 329
  },
  "origin": {
   "type": "string"
  },
  "nome": {
   "type": "string"
  },
  "destinations": {
   "type": "array",
   "items": {
    "type": "string"
   }
  },
  "hubs": {
   "type": "array",
   "items": {
    "type": "object",
    "properties": {
     "pid": {
      "pattern": "^hub:h\\d{6}$"
     },
     "lon": {
      "type": "number",
      "maximum": -126,
      "minimum": -200
     },
     "lat": {
      "type": "number",
      "minimum": 50,
      "maximum": 72
     },
     "role": {
      "enum": [
       "origin",
       "destination",
       null
      ]
     },
     "voided": {
      "type": "boolean"
     }
    },
    "required": [
     "pid",
     "lon",
     "lat",
     "name",
     "region"
    ]
   }
  }
 },
 "required": [
  "hubs",
  "destinations"
 ],
 "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== jccheesman/alaska-fuel-agents-demo/site/data/hubs.json
{"n":329,"origin":"hub:h000698","nome":"hub:h000493","destinations":["hub:h000493","hub:h000453","hub:h000639","hub:h000696","hub:h000510","hub:h000591","hub:h000638","hub:h000678","hub:h000727","hub:h000478","hub:h000557","hub:h000668","hub:h000715","hub:h000485","hub:h000483","hub:h000707","hub:h000459","hub:h000487","hub:h000490","hub:h000586"],"hubs":[{"pid":"hub:h000410","hub_id":"Hub_61","name":"Noatak (h000410)","community":"Noatak","region":"Northwest Arctic","hub_type":"Receiver","deliv_meth":"Barge or Plane","node_id":44454,"lon":-162.96979,"lat":67.56922,"capacity_gal":175700.0,"mapped_facilities":5,"mapped_remote":0,"km_to_community_facilities":0.0,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000411","hub_id":"Hub_284","name":"Karluk (h000411)","community":"Karluk","region":"Kodiak","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":47131,"lon":-154.43818,"lat":57.56435,"capacity_gal":108000.0,"mapped_facilities":3,"mapped_remote":0,"km_to_community_facilities":0.2,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000412","hub_id":"Hub_57","name":"Talkeetna (h000412)","community":"Talkeetna","region":"Railbelt","hub_type":"Supplier","deliv_meth":"Road","node_id":27982,"lon":-150.08422,"lat":62.31143,"capacity_gal":92000.0,"mapped_facilities":6,"mapped_remote":0,"km_to_community_facilities":0.7,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000413","hub_id":"Hub_339","name":"Petersburg (h000413)","community":"Petersburg","region":"Southeast","hub_type":"Receiver","deliv_meth":"Plane","node_id":35935,"lon":-133.14706,"lat":56.24034,"capacity_gal":6000.0,"mapped_facilities":1,"mapped_remote":0,"km_to_community_facilities":59.1,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000414","hub_id":"Hub_239","name":"Tazlina (h000414)","community":"Tazlina","region":"Copper River Chugach","hub_type":"Receiver","deliv_meth":"Road","node_id":47868,"lon":-145.4261,"lat":62.04448,"capacity_gal":5500.0,"mapped_facilities":1,"mapped_remote":0,"km_to_community_facilities":0.1,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000415","hub_id":"Hub_152","name":"Cantwell (h000415)","community":"Cantwell","region":"Railbelt","hub_type":"Receiver","deliv_meth":"Road","node_id":47618,"lon":-148.94165,"lat":63.38908,"capacity_gal":10000.0,"mapped_facilities":4,"mapped_remote":0,"km_to_community_facilities":0.6,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000416","hub_id":"Hub_126","name":"Ivanof Bay (h000416)","community":"Ivanof Bay","region":"Bristol Bay","hub_type":"Receiver","deliv_meth":"Barge","node_id":47834,"lon":-159.16973,"lat":55.89896,"capacity_gal":42600.0,"mapped_facilities":3,"mapped_remote":0,"km_to_community_facilities":19.8,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12],"transfer":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000417","hub_id":"Hub_290","name":"Portage (h000417)","community":"Portage","region":"Railbelt","hub_type":"Receiver","deliv_meth":"Road","node_id":494,"lon":-148.97793,"lat":60.81943,"capacity_gal":3000.0,"mapped_facilities":1,"mapped_remote":0,"km_to_community_facilities":0.2,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000418","hub_id":"Hub_29","name":"Sitka (h000418)","community":"Sitka","region":"Southeast","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":36483,"lon":-135.35399,"lat":57.0492,"capacity_gal":634829.0,"mapped_facilities":18,"mapped_remote":5,"km_to_community_facilities":2.2,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12],"transfer":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000419","hub_id":"Hub_88","name":"Kiana (h000419)","community":"Kiana","region":"Northwest Arctic","hub_type":"Supplier","deliv_meth":"Barge or Plane","node_id":44392,"lon":-160.44313,"lat":66.97294,"capacity_gal":527100.0,"mapped_facilities":10,"mapped_remote":0,"km_to_community_facilities":0.2,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000420","hub_id":"Hub_205","name":"Quinhagak (h000420)","community":"Quinhagak","region":"Lower Yukon Kuskokwim","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":41408,"lon":-161.9052,"lat":59.74964,"capacity_gal":527800.0,"mapped_facilities":6,"mapped_remote":0,"km_to_community_facilities":0.1,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000421","hub_id":"Hub_360","name":"South Naknek (h000421)","community":"South Naknek","region":"Bristol Bay","hub_type":"Receiver","deliv_meth":"Barge","node_id":40380,"lon":-157.00505,"lat":58.71447,"capacity_gal":67000.0,"mapped_facilities":4,"mapped_remote":0,"km_to_community_facilities":0.3,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000422","hub_id":"Hub_255","name":"Akiachak (h000422)","community":"Akiachak","region":"Lower Yukon Kuskokwim","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":48825,"lon":-161.48662,"lat":60.916,"capacity_gal":402000.0,"mapped_facilities":4,"mapped_remote":0,"km_to_community_facilities":1.3,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000423","hub_id":"Hub_253","name":"Skwentna (h000423)","community":"Skwentna","region":"Railbelt","hub_type":"Receiver","deliv_meth":"Road","node_id":48761,"lon":-151.20375,"lat":61.96518,"capacity_gal":4000.0,"mapped_facilities":1,"mapped_remote":0,"km_to_community_facilities":0.5,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000424","hub_id":"Hub_76","name":"Bristol Bay hub (h000424)","community":null,"region":"Bristol Bay","hub_type":"Receiver","deliv_meth":"Plane","node_id":40897,"lon":-158.5333,"lat":59.25729,"capacity_gal":9000.0,"mapped_facilities":1,"mapped_remote":0,"km_to_community_facilities":null,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000425","hub_id":"Hub_285","name":"Port Lions (h000425)","community":"Port Lions","region":"Kodiak","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":47226,"lon":-152.87836,"lat":57.86803,"capacity_gal":189700.0,"mapped_facilities":4,"mapped_remote":0,"km_to_community_facilities":0.2,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000426","hub_id":"Hub_26","name":"North Pole (h000426)","community":"North Pole","region":"Railbelt","hub_type":"Receiver","deliv_meth":"Road","node_id":30237,"lon":-147.44188,"lat":64.79208,"capacity_gal":84000.0,"mapped_facilities":6,"mapped_remote":0,"km_to_community_facilities":1.0,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000427","hub_id":"Hub_305","name":"Ketchikan (h000427)","community":"Ketchikan","region":"Southeast","hub_type":"Receiver","deliv_meth":"Plane","node_id":46151,"lon":-132.97737,"lat":56.78347,"capacity_gal":5000.0,"mapped_facilities":1,"mapped_remote":0,"km_to_community_facilities":177.6,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000428","hub_id":"Hub_310","name":"Lower Kalskag (h000428)","community":"Lower Kalskag","region":"Lower Yukon Kuskokwim","hub_type":"Receiver","deliv_meth":"Barge","node_id":41967,"lon":-160.36281,"lat":61.51206,"capacity_gal":211270.0,"mapped_facilities":3,"mapped_remote":0,"km_to_community_facilities":0.0,"access":{"transfer":[1,2,3,4,5,6,7,8,9,10,11,12],"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000429","hub_id":"Hub_217","name":"Minto (h000429)","community":"Minto","region":"Yukon-Koyukuk Upper Tanana","hub_type":"Receiver","deliv_meth":"Plane or Road","node_id":2575,"lon":-149.35712,"lat":65.14922,"capacity_gal":84000.0,"mapped_facilities":6,"mapped_remote":0,"km_to_community_facilities":0.4,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000430","hub_id":"Hub_36","name":"Cold Bay (h000430)","community":"Cold Bay","region":"Aleutians","hub_type":"Receiver","deliv_meth":"Road","node_id":39938,"lon":-162.7192,"lat":55.20355,"capacity_gal":39000.0,"mapped_facilities":7,"mapped_remote":0,"km_to_community_facilities":0.1,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000431","hub_id":"Hub_53","name":"Saint Paul (h000431)","community":"Saint Paul","region":"Aleutians","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":41260,"lon":-170.26509,"lat":57.14328,"capacity_gal":55500.0,"mapped_facilities":12,"mapped_remote":0,"km_to_community_facilities":0.9,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12],"transfer":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000432","hub_id":"Hub_8","name":"Kenai (h000432)","community":"Kenai","region":"Railbelt","hub_type":"Supplier","deliv_meth":"Road","node_id":47127,"lon":-151.29602,"lat":60.61781,"capacity_gal":128734.0,"mapped_facilities":16,"mapped_remote":0,"km_to_community_facilities":0.6,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000433","hub_id":"Hub_280","name":"Point Lay (h000433)","community":"Point Lay","region":"North Slope","hub_type":"Receiver","deliv_meth":"Barge or Road","node_id":44605,"lon":-163.01148,"lat":69.74146,"capacity_gal":573900.0,"mapped_facilities":7,"mapped_remote":0,"km_to_community_facilities":0.1,"access":{"road":[1,2,3,4,5,6,7,8,9,10,11,12],"transfer":[1,2,3,4,5,6,7,8,9,10,11,12]},"role":null,"voided":false},{"pid":"hub:h000434","hub_id":"Hub_248","name":"Seldovia (h000434)","commu
